### ISSUE TITLE
Reverse order of mix-deps-get and restore-nerves-downloads

### ISSUE THREAD

**Issue by ringlej** [nerves-project/build-tools#16]
I'm working through porting nerves systems to build with github actions. I'm using this as my reference.
One thing that I noticed is that I can avoid re-downloading the toolchain on every build by doing the equivalent of these two lines in reverse order.

[get-br-dependencies.yml](https://github.com/nerves-project/build-tools/blob/main/src/jobs/get-br-dependencies.yml#L54-L55)
```
  - mix-deps-get
  - restore-nerves-downloads
```

The mix deps.get downloads the toolchain and the restore-nerves-downloads will also have the toolchain in the cache. By reversing it, the toolchain gets pulled in via the cache once and the mix deps.get won't bother downloading it since its there.

I'm not doing any testing on circleci itself, but I suspect that it will likely reduce the build time a little on circleci if the same is done.

**Comment by jjcarstens** [comment]
Thanks @ringlej ! Created a PR to address.

Also, did you get GitHub Actions working? We experimented a while back with that and got one of our systems to build, but were undecided on using it or not. I can share the workflow we got to work

**Comment by ringlej** [comment]
Thanks.
Yes, we have GitHub actions working to build nerves_systems and using it internally. We have the actions in its own repo and plan to open source it after letting it simmer for a little while.
