### ISSUE TITLE
Use of TAG assignment when creating artifacts?

### ISSUE THREAD

**Issue by ringlej** [nerves-project/build-tools#17]
I am trying to figure out why there is a TAG= assignment done in this step and how it gets used.
I've searched the nerves mix tasks sources and couldn't find any use of env TAG when it calls `mix nerves.artifact ...`
https://github.com/nerves-project/build-tools/blob/main/src/jobs/build-system.yml#L47-L55

**Comment by jjcarstens** [comment]
Sorry @ringlej ! This looks to be unused. You're right that there is nothing in the mix task requiring it and the env var does not live past this run step
